server:
  port: 8004

spring:
  mvc:
    converters:
      preferred-json-mapper: fastjson

easyj:
  web:
    param-crypto:
      filter:
        enabled: true #默认：false（@since 0.2.2-SNAPSHOT）
        query-string-name: data
      handler:
        algorithm: AES/CBC/PKCS7Padding
        key: 12345678901234567890123456789012
        iv: 1234567890123456
        charset: UTF-8