server:
  port: 8005

spring:
  servlet:
    multipart:
      max-file-size: 5MB

easyj:
  sdk:
    tencent-cloud:
      #通用配置
      common:
        secret-id: AKIDb1B6mCMFrDJ8hz0kDQN3SgeKjriJdgSx
        secret-key: FEyRe05uSjjSv60dz3qMbaIkwrUqwmKb
        region: ap-shanghai
      #身份证识别配置，如果未配置，则自动加载通用配置
#      ocr.idcard-ocr:
#        secret-id: AKIDb1B6mCMFrDJ8hz0kDQN3SgeKjriJdgSx
#        secret-key: FEyRe05uSjjSv60dz3qMbaIkwrUqwmKb
#        region: ap-shanghai


