server:
  port: 8005


easyj:
  sdk:
    ocr:
      idcard-ocr:
        type: tencent
    tencent:
      secret-id: AKIDRtxlKhSGCxbpqL6ooX8YEooa7cw38C2d
      secret-key: Rggmrjz3wbCNHWWGkMtAuDVw71U1Zt7r
      ocr:
        idcard-ocr:
          region: ap-shanghai

spring:
  servlet:
    multipart:
      max-file-size: 5MB
