easyj:
  app:
    area: my-area
    area-name: 我的区域


test2:
  c: 3
  d: 3
  e: 3

  f: 3
  g: 3
  h: 3
  i: 3
  j: 3

  k: 3
  l: 3
  m: 3
  n: 3
  o: 3

  p: 3
  q: 3
  r: 3
  s: 3
  t: 3

  u: 3
  v: 3
  w: 3
  x: 3
  y: 3

  z: 3
