easyj:
  app:
    project: my-project
    project-name: 我的项目


test2:
  d: 4
  e: 4

  f: 4
  g: 4
  h: 4
  i: 4
  j: 4

  k: 4
  l: 4
  m: 4
  n: 4
  o: 4

  p: 4
  q: 4
  r: 4
  s: 4
  t: 4

  u: 4
  v: 4
  w: 4
  x: 4
  y: 4

  z: 4
